module.exports.authService = require("./auth.service")
module.exports.userService = require("./user.service")
module.exports.emailService = require("./email.service")
module.exports.snackTypeService = require("./snackType.service")
module.exports.productsService = require("./products.service")
module.exports.transactionService = require("./transaction.service")